### ISSUE TITLE
Should WebAuthn work?

### ISSUE THREAD

**Issue by systemcrash** [chiff-app/chiff-ios#28]
Hello :)

Should webauthn work?

When I try to add a security key for any website, nothing happens in chiff.

I'm used to krypt.co (who have a good webauthn/security key implementation).

Could not get the "register security key" dialogue in ff/chrome/safari.  The point of WebAuthn is so that passwords do not get fished. :)

**Comment by bas-d** [comment]
Thanks for notifying us. WebAuthn is supported in Google Chrome and Microsoft Edge. However, it seems there is bug with loading notifications in version 3.2.0, which causes WebAuthn (among other things) to not work properly. A hotfix version (3.2.1) has just been released, but is still pending review in the Chrome Web Store. Usually it will be accepted within a day. 
If that's too long, you can download the latest version already [here](https://github.com/chiff-app/chiff-ios/files/11238575/chiff-browser-chrome-3.2.1.zip) and run it locally [1]:

1. Open the Extension Management page by navigating to chrome://extensions. The Extension Management page can also be opened by clicking on the Chrome menu, hovering over More Tools then selecting Extensions.
2. Enable Developer Mode by clicking the toggle switch next to Developer mode.
3. Click the LOAD UNPACKED button and select the extension directory.
4. Load Extension
![image](https://user-images.githubusercontent.com/7903735/232190866-eade7b69-43a0-4d54-994a-21d3144d7b47.png)

Note that this will run a second instance of the Chiff extension in your browser, so you will need to pair again. It's probably easiest to temporarily disable the chrome web store version, like this:

<img width="421" alt="Screenshot 2023-04-15 at 08 37 16" src="https://user-images.githubusercontent.com/7903735/232191215-725ee4df-ac63-48ee-9349-767ac8fe0386.png">

I recommend switching back to the chrome web store version as soon as version 3.2.1 is accepted, otherwise new updates won't get installed automatically. Let me know if anything is unclear.

Apologies for the inconvenience.

[1] https://developer.chrome.com/docs/extensions/mv2/getstarted/#manifest

**Comment by systemcrash** [comment]
I notice Firefox is absent from the list there.

Should it work or is it just not yet supported? Ff is my daily driver.

**Comment by bas-d** [comment]
Not yet supported, sorry! Chrome web store version 3.2.1 has been published by the way.

**Comment by systemcrash** [comment]
Thanks!

**Comment by systemcrash** [comment]
While I'm asking is "Firefox doesn't work" a question of bugs here or
something ff hasn't implementes yet?

**Comment by bas-d** [comment]
It hasn't been implemented yet. It needed a different approach than on chromium-based browsers, and haven't looked into it yet. Also, you are the first person asking for it 😄.
I'll have a look how much work it is to implement, but can't make any promises..

**Comment by systemcrash** [comment]
Ok, thanks. Isn't it an API? I.e. (Largely) universal?

**Comment by bas-d** [comment]
There is an API for the website (*Relying Party* in WebAuthn definitions), but not for a browser extension that serves as a authenticator.

**Comment by systemcrash** [comment]
What does krypt have to say on the subject?

Their implementation seems fine. Some sites moved to something newer and
broke some Auth moments.

**Comment by systemcrash** [comment]
Did you take a look at chiff for firefox?

**Comment by bas-d** [comment]
Sorry for the delay. I'm looking into it, think I should have something working soon, I'll keep you posted!

**Comment by bas-d** [comment]
I've just released a new version for firefox (3.3.1), where support for Firefox has been added. Hope it works as expected, otherwise let me know!

**Comment by systemcrash** [comment]
I get 

"there is no AWS endpoint in the session data."

when I try to scan the (FF) barcode from iOS app.

**Comment by systemcrash** [comment]
Let me know whether I should open a new issue...
