### ISSUE TITLE
FF web ext

### ISSUE THREAD

**Issue by systemcrash** [chiff-app/chiff-ios#34]
Didn't know where else to log this. 

Chiff takes over authentication too aggressively. FF saved passwords no longer function at all. 

If the ext augmented firefox, rather than replacing its behaviour, that would be great. 

This would ease migration of "saved in FF" to "saved in Chiff" more quickly and easily.

**Comment by bas-d** [comment]
Chiff indeed turns off the browser's password manager because it caused confusion with our less tech-savvy users. However, I agree that it's not ideal that it can't be turned on again. Will add a setting that allows you to override this, which should be available in the next release of the extension.

**Comment by bas-d** [comment]
Will be fixed in v3.4.0 of the extension.
